### PR TITLE
Production/cafevdb/stable27

### PR DESCRIPTION
**Pull request by rotdrop**
A couple of updates

- claim to support PHP >= 8, NC 25 - 27
- clarify use of username column in README.md
- properly log exceptions in DataQuery classs
- implement ISearchableGroupBackend
- fix use of disabled column (FIND_GROUP_USERS, BELONGS_TO_ADMIN)
- use LEFT JOIN rather than selecting from multiple tables
- fix the issue that the cache cannot store objects, just arrays
- protect statement prepare with try-catch
- allow delegation of admin settings

This PR supersedes my other PRs.

### CODE REVIEW

**Comment by rotdrop** [comment]
Fixes

- #168
- #173
- #189 
- #184 by changing the SQL example in the README.md
- #188

**Comment by pacohope** [comment]
Thanks for doing this. I'm not a developer on here, but I wanted to confirm that I'm running Nextcloud 27.1.1 with php8.2 on FreeBSD 13.2-RELEASE and I just installed the [version referenced by this PR](https://github.com/rotdrop/user_sql/tree/production/cafevdb/stable27) and it is working on my system. I mean, I know that's not much: it's just one dude saying "works on my machine". But hey, _it works on my machine_. Thanks for making the PR available!

**Comment by xylo** [comment]
Any news on this PR?

**Comment by dregad** [comment]
@rotdrop many thanks for this, you're a life saver !

And finally this got merged, but we still need to have a new version tagged... @mlojewski-me ?

**Pull request merged**
