### PR TITLE
Revert "code for supervisor mode removed"

### PR DESCRIPTION
**Pull request by mlojewski-me**
Reverts nextcloud/user_sql#21

### CODE REVIEW

**Comment by tomtomas99911** [comment]
Legality is problem of owner of server. Developers just develops functions - and more useful functions of this addon are our goal.

It is also necessary to say that Nextcloud are using people out of EU, so they does not care about GDPR.

In my honest opinion, more features are good things because if this function is disabled in default there is no problem.

**Comment by poVoq** [comment]
Going by the comments from the original pull request that removed this feature, I indeed also think this is a functionality that should not be included in this app, but rather be taken care off with the separate "impersonate" app.

maybe @tomtomas99911 can explain a bit better what functionality this implementation offers that the impersonate app doesn't? Also, why can't one do a pull request to the impersonate app to include that functionality instead of introducing it "through the backdoor" of another mostly unrelated app that is user_sql?

**Comment by gpgmailencrypt** [comment]
> It is also necessary to say that Nextcloud are using people out of EU
Exactly. That's why such a function has to be in a separate app. If this function is important, then it is of general interest, not just for users of user_sql. If the app "retention" doesn't fully fit your needs, presumably it would be better to implement  this  feature there. Depending of the country you live in then you can use this feature without bringing other users in legal trouble.
BTW an authentication app is not for the end user, it's for the administrator and thus IMHO more something concerning the owner of the server.

**Comment by UncleAlbie** [comment]
@poVoq The Impersonate plugin doesn't offer a supervision as an alternative authentication method. As the description says: 

"By installing the impersonate app of your Nextcloud you enable administrators to impersonate other users on the Nextcloud server. This is especially useful for debugging issues reported by users."

The Impersonate plugin may offer a similar function but for a very different use case.

Honestly, I don't see any legal issues with this function as it is disabled by default and it's up to the administrator to decide if he/she can legally activate it. I believe it's appropriate to include this function to this plugin as it only extends the authentication method. However, I think that putting some kind of legal warning to the supervisor settings tab might be a good idea. But administrators should be able to make their informed decision as they are responsible for the legality of the software they use.

**Comment by tomtomas99911** [comment]
As @UncleAlbie say, Impersonate plugin is for other kind of use case.

I think that this is good function and there is no real or legal obstacle to implement it back. Especially if we add "warning" to the plugin menu.

**Comment by poVoq** [comment]
The differentiation between this and impersonate seems to be in wording but not in actual function though?

I agree that if disable by default and with a clear warning it might be ok, but I still think it would be better/cleaner to implement such a functionality as a separate app.

**Comment by UncleAlbie** [comment]
@poVoq No. There's an actual difference between the supervisor function and the Impersonate plugin.

The supervision works with the database configured for this plugin. It authenticates the user against the supervisor's password. That way one can use it to login via mobile and desktop apps as well as API. Implementing this function inside this plugin benefits from the integration while not changing the behaviour of the plugin when disabled (default). I honestly don't see the issue here. Though, legal warning of some kind would be a good thing for sure.

**Comment by UncleAlbie** [comment]
@gpgmailencrypt Since you seem well educated on the legal issue. Would you be willing to implement legal warning?

**Comment by tomtomas99911** [comment]
So the conclusion is, that this function is OK in default disabled state and with legal warning?

**Comment by mlojewski-me** [comment]
In my mind. Yes.

**Comment by gpgmailencrypt** [comment]
Still having problems with it. You can't solve it with a simple legal statement. It's a backdoor and this might be illegal.You would exclude users (including me and thus no commits from my side any more) from being able to use user_sql.

But leave the legal part away. I understand that some people want this function. The main question is, why should it be part of user_sql, or exactly: what is sql database specific in this function? No other authentication app includes this function. 

If this function is so important, it is also important to users of other authentication systems. so it should part in a separate app.

**Comment by tomtomas99911** [comment]
I think, we have to move this pull ahead. It is still the same around. I think that warning and default disable state of this function is a reasonable compromise.

**Comment by mlojewski-me** [comment]
I personally don't like this solution. For me it has nothing in common with sql authentication and it should be available in separate app. @tomtomas99911 Have you thought about making a new app, just with that function?

**Comment by tomtomas99911** [comment]
Yes, but new app with this function is imho unnecessarily complicated.

**Comment by UncleAlbie** [comment]
@mlojewski-me any conclusion here?

**Comment by mlojewski-me** [comment]
I will not merge this pull request. This in not functionality what this app is made for. It should be feature of another app.

**Pull request closed without merging**
