### PR TITLE
Drupal 7 authentication

### PR DESCRIPTION
**Pull request by WardinT**

### CODE REVIEW

**Comment by mlojewski-me** [comment]
Thanks for the request but I don't think that's a good commit. I will loop up at this later, when I find some time. But it's definitely a good change.

**Comment by mlojewski-me** [comment]
Commit made.
Thanks for code delivery :)
https://github.com/nextcloud/user_sql/commit/ebcdaa813b7af5efe935a955f3e0976f8de9b719

**Comment by aanderse** [comment]
@mlojewski-me This code was removed in commit c1cc89f456231ecb853fc7d3a4d47ec6dcaa41f0 but the comment simply says "'lib' rewritten." Was it intentional to remove this code in that commit? Is there any chance of resurrecting this functionality?
@WardinT Do you still have any interest in this functionality?

**Comment by mlojewski-me** [comment]
I think 'Portable PHP password' is the same algorithm, but I'm not sure.

**Comment by BrandonKerr** [comment]
@mlojewski-me I reviewed the 'Portable PHP Password' option and found a few changes that needed to be made for it to work with Drupal 7. Drupal 7 uses sha512 instead of md5 and had a couple other changes as noted below:
`@@ -75,15 +75,15 @@
             return null;
         }
 
-        $hash = md5($salt . $password, true);
+        $hash = hash('sha512', $salt . $password, true);
         do {
-            $hash = md5($hash . $password, true);
+            $hash = hash('sha512', $hash . $password, true);
         } while (--$count);
 
         $output = substr($setting, 0, 12);
-        $output .= $this->encode64($hash, 16);
+        $output .= $this->encode64($hash, strlen($hash));
 
-        return $output;
+        return substr($output, 0, 55);
     }`
How would you recommend bringing these changes back in? I assume other apps use Phpass as it is now. Would it be better to bring in a dedicated Drupal 7 option again, or add an option to Portal PHP password?

**Comment by WardinT** [comment]
I'd prefer the dedicated Drupal 7 option.

**Comment by BrandonKerr** [comment]
I've worked up my changes as a separate file for a dedicated Drupal 7 option, which extends Phpass in order to be as unobtrusive as possible. Alternatively, we could update Phpass to take optional arguments, but I see that you have open issue #46 which sounds like it's along those same lines and I'd prefer to not get in your way for that.
Would it be best to fork and create a new pull request, or would you prefer a just adding the file here so you can work it into this existing PR (pending your approval, of course)?

**Comment by mlojewski-me** [comment]
I think issue #46 is going to take a long time to finish, so in my mind the best option is to make PR with dedicated class for Drupal 7, which extends Phpass.
When the PR is ready I will check it and approve.

**Comment by BrandonKerr** [comment]
Thanks for the feedback. There's a new PR for your review now.

**Comment by mlojewski-me** [comment]
Moved to #66

**Pull request closed without merging**
